### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by dpw** [spacejam/loghisto#4]
Please add a LICENSE file to cover the project as a whole.  While most of the *.go files link to the Apache 2 license, the *_test.go files do not, so it is unclear whether whether they are licensed for distribution.  Having a top-level LICENSE file makes checking the licensing status of projects a lot easier.

**Comment by ldm5180** [comment]
+1

**Comment by spacejam** [comment]
Apache 2 license added!
